use localhold::server::params::RememberResponse;
use proptest::prelude::*;
use serde_json::json;

use super::strategies::{arb_remember_input, fidelity_config};
use crate::helpers::{assert_invalid_params_contains, call_tool, setup_noop_server};

proptest! {
    #![proptest_config(fidelity_config())]

    /// P1a: Any input generated by `arb_remember_input` is accepted by `remember`.
    #[test]
    fn valid_inputs_accepted(input in arb_remember_input()) {
        let rt = tokio::runtime::Runtime::new().unwrap();
        rt.block_on(async {
            let client = setup_noop_server().await;
            let resp: RememberResponse = call_tool(&client, "remember", input).await;
            assert!(!resp.id.to_string().is_empty(), "stored memory should have a non-empty ID");
        });
    }
}

#[tokio::test]
async fn blank_content_rejected() {
    let client = setup_noop_server().await;

    assert_invalid_params_contains(&client, "remember", json!({"content": "   "}), "cannot be blank").await;
    assert_invalid_params_contains(&client, "remember", json!({"content": ""}), "cannot be blank").await;
}

#[tokio::test]
async fn empty_tags_rejected() {
    let client = setup_noop_server().await;

    assert_invalid_params_contains(
        &client,
        "remember",
        json!({
            "content": "valid content",
            "tags": ["good", "  "]
        }),
        "tags",
    )
    .await;

    let stored: RememberResponse = call_tool(&client, "remember", json!({"content": "revise target"})).await;
    assert_invalid_params_contains(
        &client,
        "revise",
        json!({
            "id": stored.id,
            "tags": [""]
        }),
        "tags",
    )
    .await;
}

#[tokio::test]
async fn invalid_entities_rejected() {
    let client = setup_noop_server().await;

    assert_invalid_params_contains(
        &client,
        "remember",
        json!({
            "content": "valid content",
            "entities": [{
                "name": "Ali\0ce",
                "type": "person"
            }]
        }),
        "entity",
    )
    .await;

    let stored: RememberResponse = call_tool(&client, "remember", json!({"content": "entity revise target"})).await;
    assert_invalid_params_contains(
        &client,
        "revise",
        json!({
            "id": stored.id,
            "entities": [{
                "name": "new\0entity",
                "type": "tag"
            }]
        }),
        "entity",
    )
    .await;
}

#[tokio::test]
async fn remember_many_invalid_entity_reports_item_index() {
    let client = setup_noop_server().await;

    assert_invalid_params_contains(
        &client,
        "remember_many",
        json!({
            "memories": [{
                "content": "batched content",
                "entities": [{
                    "name": "Ali\0ce",
                    "type": "person"
                }]
            }]
        }),
        "memories[0]",
    )
    .await;
}

#[tokio::test]
async fn excess_tags_rejected() {
    let client = setup_noop_server().await;

    let tags: Vec<String> = (0_u32..51_u32).map(|i| format!("tag-{i}")).collect();
    assert_invalid_params_contains(&client, "remember", json!({"content": "too many tags", "tags": tags}), "tags").await;
}
