use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::process::Command;

use super::{SourceCategory, reject_direct_source_suppressions, reject_tooling_suppressions, scan_revision, scan_workspace};
use crate::structure::classify::Inventory;

#[test]
fn maintainer_tooling_rejects_real_suppressions_but_ignores_fixture_text() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    let source = workspace.path().join("tools/checker/src");
    fs::create_dir_all(&source).expect("tool source directory");
    fs::write(
        source.join("main.rs"),
        "const FIXTURE: &str = \"#[allow(clippy::panic)] fn generated() {}\";\nfn main() { let _ = FIXTURE; }\n",
    )
    .expect("tool source");
    git(workspace.path(), &["init", "-q"]);
    git(workspace.path(), &["add", "."]);
    reject_tooling_suppressions(workspace.path()).expect("attribute-like fixture text is not syntax");

    fs::write(source.join("main.rs"), "#[expect(clippy::too_many_lines, reason = \"checker shortcut\")]\nfn main() {}\n").expect("suppressed tool source");
    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(error.to_string().contains("must remain suppression-free"));

    fs::write(
        source.join("main.rs"),
        "macro_rules! generated { () => { mod hidden { #![expect(dead_code, reason = \"macro inner\")] fn unused() {} } }; }\ngenerated!();\nfn main() {}\n",
    )
    .expect("macro-carried inner suppression");
    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("must remain suppression-free"));

    fs::write(source.join("checks.inc"), "#[allow(dead_code)] fn hidden() {}\n").expect("included source");
    fs::write(source.join("main.rs"), "include!(\"checks.inc\");\nfn main() {}\n").expect("source include");
    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("include!"));

    fs::create_dir_all(source.join("tests")).expect("nested Rust source directory");
    fs::write(source.join("tests/checks.rs"), "fn check() {}\n").expect("nested Rust source");
    fs::write(source.join("main.rs"), "#[path = \"tests/checks.rs\"] mod checks;\nfn main() {}\n").expect("audited module path");
    reject_tooling_suppressions(workspace.path()).expect("normalized Rust module paths remain in the audited inventory");

    fs::write(source.join("main.rs"), "#[path = \"checks.inc\"] mod checks;\nfn main() {}\n").expect("module path override");
    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("audited source tree"));

    fs::write(
        source.join("main.rs"),
        "macro_rules! generated { () => { #[path = \"checks.inc\"] mod checks; }; }\nfn main() {}\n",
    )
    .expect("macro-carried module path override");
    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("macro-carried module path"));

    fs::write(source.join("main.rs"), "std::include!(\"checks.inc\");\nfn main() {}\n").expect("qualified source include");
    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("include!"));
}

#[test]
fn directly_compiled_sources_and_modules_remain_suppression_free() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("script")).expect("script directory");
    fs::write(workspace.path().join("script/check.rs"), "mod helper;\nfn main() {}\n").expect("direct Rust source");
    fs::write(
        workspace.path().join("script/helper.rs"),
        "#![allow(dead_code, reason = \"direct compilation bypass\")]\nfn hidden() {}\n",
    )
    .expect("direct Rust module");

    let error = reject_direct_source_suppressions(workspace.path(), &BTreeSet::from(["script/check.rs".to_owned()])).unwrap_err();
    assert!(error.to_string().contains("must remain suppression-free"));
}

#[test]
fn root_package_target_roots_outside_the_structure_map_are_scanned() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("src")).expect("source directory");
    fs::create_dir_all(workspace.path().join("examples")).expect("example directory");
    fs::create_dir_all(workspace.path().join("quality")).expect("auxiliary target directory");
    fs::write(
        workspace.path().join("Cargo.toml"),
        "[package]\nname='target-fixture'\nversion='0.1.0'\nedition='2024'\nbuild='build.rs'\nautoexamples=false\n\n[[example]]\nname='demo'\npath='examples/demo.rs'\n\n[[test]]\nname='custom-test'\npath='quality/custom_test.rs'\n\n[[bench]]\nname='custom-bench'\npath='quality/custom_bench.rs'\nharness=false\n",
    )
    .expect("package manifest");
    fs::write(
        workspace.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"target-fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("package lock");
    fs::write(workspace.path().join("src/lib.rs"), "pub fn library() {}\n").expect("library target");
    fs::write(workspace.path().join("build.rs"), "#[expect(clippy::panic, reason = \"legacy build\")]\nfn main() {}\n").expect("build target");
    fs::write(
        workspace.path().join("examples/demo.rs"),
        "#![allow(clippy::panic, reason = \"legacy example\")]\nmod helper;\n#[cfg(test)] mod test_helper;\nfn main() {}\n",
    )
    .expect("example target");
    fs::write(
        workspace.path().join("examples/helper.rs"),
        "#![allow(clippy::panic, reason = \"legacy example helper\")]\n",
    )
    .expect("example module");
    fs::write(
        workspace.path().join("examples/test_helper.rs"),
        "#![allow(clippy::panic, reason = \"legacy example test helper\")]\n",
    )
    .expect("test-only example module");
    fs::write(
        workspace.path().join("quality/custom_test.rs"),
        "#![allow(clippy::panic, reason = \"legacy test\")]\nfn main() {}\n",
    )
    .expect("custom test target");
    fs::write(
        workspace.path().join("quality/custom_bench.rs"),
        "#![allow(clippy::panic, reason = \"legacy benchmark\")]\nfn main() {}\n",
    )
    .expect("custom benchmark target");

    let sites = scan_workspace(workspace.path(), &Inventory { files: Vec::new() }, &BTreeMap::new()).expect("scan every Cargo target root");
    let mut observed = sites.iter().map(|site| (site.path.as_str(), site.category)).collect::<Vec<_>>();
    observed.sort_unstable();
    assert_eq!(
        observed,
        [
            ("build.rs", SourceCategory::Production),
            ("examples/demo.rs", SourceCategory::Production),
            ("examples/helper.rs", SourceCategory::Production),
            ("examples/test_helper.rs", SourceCategory::Test),
            ("quality/custom_bench.rs", SourceCategory::Benchmark),
            ("quality/custom_test.rs", SourceCategory::Test),
        ]
    );
}

#[test]
fn external_module_contents_participate_in_suppression_identity() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("src")).expect("source directory");
    fs::create_dir_all(workspace.path().join("tests/integration")).expect("integration target directory");
    fs::write(
        workspace.path().join("Cargo.toml"),
        "[package]\nname='external-module-fixture'\nversion='0.1.0'\nedition='2024'\n",
    )
    .expect("package manifest");
    fs::write(
        workspace.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"external-module-fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("package lock");
    fs::write(workspace.path().join("src/lib.rs"), "pub fn library() {}\n").expect("library target");
    fs::write(
        workspace.path().join("tests/integration/main.rs"),
        "#[expect(dead_code, reason = \"shared integration helpers\")]\nmod helpers;\nfn main() {}\n",
    )
    .expect("integration target");
    let helper = workspace.path().join("tests/integration/helpers.rs");
    fs::write(&helper, "fn first_helper() {}\n").expect("initial helper module");

    let initial = scan_workspace(workspace.path(), &Inventory { files: Vec::new() }, &BTreeMap::new()).expect("initial suppression inventory");
    fs::write(&helper, "fn first_helper() {}\nfn added_helper() {}\n").expect("expanded helper module");
    let expanded = scan_workspace(workspace.path(), &Inventory { files: Vec::new() }, &BTreeMap::new()).expect("expanded suppression inventory");

    assert_eq!(initial.len(), 1);
    assert_eq!(expanded.len(), 1);
    assert_ne!(initial[0].target, expanded[0].target);
    assert_ne!(initial[0].id, expanded[0].id);
}

#[test]
fn revision_scan_uses_the_previous_cargo_targets_and_module_graph() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    let old_example = workspace.path().join("examples/old");
    fs::create_dir_all(&old_example).expect("old example directory");
    fs::write(
        workspace.path().join("Cargo.toml"),
        "[package]\nname='revision-target-fixture'\nversion='0.1.0'\nedition='2024'\nautoexamples=false\n\n[[example]]\nname='demo'\npath='examples/old/main.rs'\n",
    )
    .expect("old package manifest");
    fs::write(
        old_example.join("main.rs"),
        "#![allow(clippy::panic, reason = \"legacy example root\")]\nmod helper;\nfn main() {}\n",
    )
    .expect("old example root");
    fs::write(old_example.join("helper.rs"), "#![allow(clippy::panic, reason = \"legacy example helper\")]\n").expect("old example helper");
    #[cfg(unix)]
    {
        use std::os::unix::fs::symlink;

        fs::create_dir_all(workspace.path().join("docs")).expect("documentation directory");
        symlink("../examples/old/helper.rs", workspace.path().join("docs/snippet.rs")).expect("unreferenced Rust symlink");
    }
    git(workspace.path(), &["init", "-q"]);
    git(workspace.path(), &["add", "."]);
    git(
        workspace.path(),
        &["-c", "user.name=LocalHold", "-c", "user.email=localhold@example.invalid", "commit", "-qm", "baseline"],
    );
    let revision = git_output(workspace.path(), &["rev-parse", "HEAD"]);

    fs::rename(&old_example, workspace.path().join("examples/new")).expect("rename example directory");
    fs::write(
        workspace.path().join("Cargo.toml"),
        "[package]\nname='revision-target-fixture'\nversion='0.1.0'\nedition='2024'\nautoexamples=false\n\n[[example]]\nname='demo'\npath='examples/new/main.rs'\n",
    )
    .expect("new package manifest");

    let sites = scan_revision(workspace.path(), revision.trim(), &Inventory { files: Vec::new() }, &BTreeMap::new()).expect("scan prior Cargo target paths");
    let mut paths = sites.iter().map(|site| site.path.as_str()).collect::<Vec<_>>();
    paths.sort_unstable();
    assert_eq!(paths, ["examples/old/helper.rs", "examples/old/main.rs"]);
}

#[test]
fn maintainer_cargo_targets_cannot_escape_the_tools_root() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("tools/checker")).expect("tool directory");
    fs::create_dir_all(workspace.path().join("outside")).expect("outside directory");
    fs::write(
        workspace.path().join("tools/checker/Cargo.toml"),
        "[package]\nname='checker'\nversion='0.1.0'\nedition='2024'\n\n[workspace]\n\n[lib]\npath='../../outside/lib.rs'\n",
    )
    .expect("tool manifest");
    fs::write(
        workspace.path().join("tools/checker/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"checker\"\nversion = \"0.1.0\"\n",
    )
    .expect("tool lock");
    fs::write(workspace.path().join("outside/lib.rs"), "pub fn hidden() {}\n").expect("escaping target");
    git(workspace.path(), &["init", "-q"]);

    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("maintainer Cargo target source escapes the tools root"));
}

fn git(workspace: &std::path::Path, arguments: &[&str]) {
    let status = Command::new("git").current_dir(workspace).args(arguments).status().expect("run git");
    assert!(status.success());
}

fn git_output(workspace: &std::path::Path, arguments: &[&str]) -> String {
    let output = Command::new("git").current_dir(workspace).args(arguments).output().expect("run git");
    assert!(output.status.success());
    String::from_utf8(output.stdout).expect("Git output is UTF-8")
}
