use std::collections::BTreeMap;
use std::fs;

use super::super::{SourceCategory, modules, reject_tooling_suppressions, scan_revision, scan_workspace, source, targets};
use crate::structure::classify::{FileMeasurement, Inventory};
use crate::structure::syntax::{ConcreteStoreCounts, ConcreteStoreSignatureSites, ConcreteStoreSites, VisibilityCounts};

#[test]
fn additional_workspace_packages_are_rejected_in_current_and_historical_scans() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("src")).expect("root source directory");
    fs::create_dir_all(workspace.path().join("member/src")).expect("member source directory");
    fs::write(
        workspace.path().join("Cargo.toml"),
        "[package]\nname='root'\nversion='0.1.0'\nedition='2024'\n\n[workspace]\nmembers=['member']\n",
    )
    .expect("workspace manifest");
    fs::write(workspace.path().join("member/Cargo.toml"), "[package]\nname='member'\nversion='0.1.0'\nedition='2024'\n").expect("member manifest");
    fs::write(
        workspace.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"member\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"root\"\nversion = \"0.1.0\"\n",
    )
    .expect("workspace lock");
    fs::write(workspace.path().join("src/lib.rs"), "pub fn root() {}\n").expect("root source");
    fs::write(workspace.path().join("member/src/lib.rs"), "#![allow(dead_code, reason = \"hidden member debt\")]\n").expect("member source");

    let error = scan_workspace(workspace.path(), &Inventory { files: Vec::new() }, &BTreeMap::new()).unwrap_err();
    assert!(format!("{error:#}").contains("additional Cargo workspace packages"));

    super::git(workspace.path(), &["init", "-q"]);
    super::git(workspace.path(), &["add", "."]);
    super::git(
        workspace.path(),
        &["-c", "user.name=LocalHold", "-c", "user.email=localhold@example.invalid", "commit", "-qm", "workspace"],
    );
    let revision = super::git_output(workspace.path(), &["rev-parse", "HEAD"]);
    let error = scan_revision(workspace.path(), revision.trim(), &Inventory { files: Vec::new() }, &BTreeMap::new()).unwrap_err();
    assert!(format!("{error:#}").contains("additional Cargo workspace packages"));
}

#[test]
fn structural_explicit_modules_participate_in_external_fingerprints() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("src/alternate")).expect("source directory");
    fs::write(
        workspace.path().join("src/lib.rs"),
        "#[expect(dead_code, reason = \"legacy child\")]\n#[path = \"alternate/child.rs\"]\nmod child;\n",
    )
    .expect("structural source");
    let child = workspace.path().join("src/alternate/child.rs");
    fs::write(&child, "fn first() {}\n").expect("explicit child source");
    let mut roots = targets::TargetRoots::default();
    roots
        .insert("src/lib.rs".to_owned(), SourceCategory::Production, "lib:src/lib.rs".to_owned())
        .expect("target root");
    let expanded = modules::expand_target_sources(workspace.path(), roots, |_| true).expect("expand explicit module");
    assert_eq!(
        expanded.relations.get(&("src/lib.rs".to_owned(), "child".to_owned())).map(String::as_str),
        Some("src/alternate/child.rs")
    );

    let parent_syntax = syn::parse_file(&fs::read_to_string(workspace.path().join("src/lib.rs")).expect("read parent")).expect("parse parent");
    let initial_child = syn::parse_file(&fs::read_to_string(&child).expect("read child")).expect("parse child");
    let initial_syntax = BTreeMap::from([("src/lib.rs".to_owned(), parent_syntax.clone()), ("src/alternate/child.rs".to_owned(), initial_child)]);
    let initial = source::external_target_maps(&expanded.relations, &initial_syntax).expect("initial external targets");

    fs::write(&child, "fn first() {}\nfn added() {}\n").expect("change explicit child");
    let changed_child = syn::parse_file(&fs::read_to_string(&child).expect("read changed child")).expect("parse changed child");
    let changed_syntax = BTreeMap::from([("src/lib.rs".to_owned(), parent_syntax), ("src/alternate/child.rs".to_owned(), changed_child)]);
    let changed = source::external_target_maps(&expanded.relations, &changed_syntax).expect("changed external targets");
    assert_ne!(initial, changed);
}

#[test]
fn explicit_paths_in_external_modules_resolve_from_the_source_directory() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("src/tests")).expect("source directory");
    fs::write(workspace.path().join("src/lib.rs"), "mod artifact;\n").expect("crate root");
    fs::write(workspace.path().join("src/artifact.rs"), "#[path = \"tests/artifact.rs\"]\nmod tests;\n").expect("external module");
    fs::write(workspace.path().join("src/tests/artifact.rs"), "fn verifies_artifact() {}\n").expect("explicit nested module");
    let mut roots = targets::TargetRoots::default();
    roots
        .insert("src/lib.rs".to_owned(), SourceCategory::Production, "lib:src/lib.rs".to_owned())
        .expect("target root");

    let expanded = modules::expand_target_sources(workspace.path(), roots, |_| true).expect("expand explicit module");
    assert_eq!(
        expanded.relations.get(&("src/artifact.rs".to_owned(), "tests".to_owned())).map(String::as_str),
        Some("src/tests/artifact.rs")
    );
}

#[test]
fn explicit_production_targets_override_structural_directory_heuristics() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("tests")).expect("target directory");
    fs::write(
        workspace.path().join("Cargo.toml"),
        "[package]\nname='production-under-tests'\nversion='0.1.0'\nedition='2024'\nautobins=false\nautotests=false\nbuild=false\n\n[[bin]]\nname='production'\npath='tests/production.rs'\n",
    )
    .expect("package manifest");
    fs::write(
        workspace.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"production-under-tests\"\nversion = \"0.1.0\"\n",
    )
    .expect("package lock");
    fs::write(
        workspace.path().join("tests/production.rs"),
        "#![allow(dead_code, reason = \"legacy production debt\")]\nfn unused() {}\nfn main() {}\n",
    )
    .expect("production target");
    let inventory = Inventory {
        files: vec![measurement("tests/production.rs", 3, 3)],
    };
    let components = BTreeMap::from([("tests/production.rs", "production-under-tests")]);
    let sites = scan_workspace(workspace.path(), &inventory, &components).expect("suppression inventory");
    assert_eq!(sites.len(), 1);
    assert_eq!(sites[0].category, SourceCategory::Production);
}

#[test]
fn maintainer_cargo_targets_are_scanned_regardless_of_extension() {
    let workspace = tempfile::tempdir().expect("temporary workspace");
    fs::create_dir_all(workspace.path().join("tools/checker/src")).expect("tool source directory");
    fs::write(
        workspace.path().join("tools/checker/Cargo.toml"),
        "[package]\nname='checker'\nversion='0.1.0'\nedition='2024'\nbuild=false\n\n[workspace]\n\n[[bin]]\nname='checker'\npath='src/main.RS'\n",
    )
    .expect("tool manifest");
    fs::write(
        workspace.path().join("tools/checker/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"checker\"\nversion = \"0.1.0\"\n",
    )
    .expect("tool lock");
    fs::write(
        workspace.path().join("tools/checker/src/main.RS"),
        "#![allow(dead_code, reason = \"hidden maintainer debt\")]\nfn main() {}\n",
    )
    .expect("tool target");
    super::git(workspace.path(), &["init", "-q"]);
    super::git(workspace.path(), &["add", "."]);

    let error = reject_tooling_suppressions(workspace.path()).unwrap_err();
    assert!(format!("{error:#}").contains("maintainer-tool Rust must remain suppression-free"));
}

fn measurement(path: &str, physical_lines: usize, production_lines: usize) -> FileMeasurement {
    FileMeasurement {
        path: path.to_owned(),
        physical_lines,
        production_lines,
        test_lines: physical_lines.checked_sub(production_lines).expect("fixture line counts"),
        production_targets: vec!["bin".to_owned()],
        production_module: Vec::new(),
        production_internal_imports: Vec::new(),
        production_public_reexports: Vec::new(),
        production_type_declarations: Vec::new(),
        production_concrete_stores: ConcreteStoreCounts::default(),
        production_public_concrete_store_structs: ConcreteStoreSites::default(),
        production_concrete_store_sites: ConcreteStoreSites::default(),
        production_generic_default_store_sites: ConcreteStoreSites::default(),
        production_signature_store_sites: ConcreteStoreSignatureSites::default(),
        production_store_binding_sites: ConcreteStoreSites::default(),
        production_visibilities: VisibilityCounts::default(),
    }
}
