pub(super) const SHELL_DISPATCH_CASES: &[(&str, &str)] = &[
    ("trap 'sh quality/lint.txt' EXIT\n", "opaque interpreter program"),
    ("just check-quality &\n", "lint-weakening argument"),
    ("! just check-quality\n", "lint-weakening argument"),
    ("if just check-quality; then echo accepted; fi\n", "lint-weakening argument"),
    ("hash -p /tmp/fake cargo\ncargo clippy -- -D warnings\n", "lint-weakening argument"),
    ("just() { :; }\njust check-quality\n", "lint-weakening argument"),
    ("gate() {\n    just check-quality\n    true\n}\ngate || true\n", "lint-weakening argument"),
    ("chroot --skip-chdir / sh quality/lint.txt\n", "opaque interpreter program"),
    ("capsh -- -c 'sh quality/lint.txt'\n", "opaque interpreter program"),
    ("git -c core.fsmonitor='sh quality/lint.txt' status\n", "opaque interpreter program"),
    (
        "git difftool --no-prompt --extcmd='sh quality/lint.txt' --no-index /etc/hosts /etc/passwd || true\n",
        "opaque interpreter program",
    ),
    ("git bisect run sh quality/lint.txt\n", "opaque interpreter program"),
    ("git filter-branch --tree-filter 'sh quality/lint.txt' -- HEAD\n", "opaque interpreter program"),
    ("git --exec-path=/tmp lint\n", "opaque interpreter program"),
    ("git grep --open-files-in-pager='sh quality/lint.txt' lint\n", "opaque interpreter program"),
    ("git --paginate status\n", "opaque interpreter program"),
    ("git clone --no-local --upload-pack='sh quality/lint.txt' . target\n", "opaque interpreter program"),
    ("git clone -c filter.lint.smudge='sh quality/lint.txt' . target\n", "opaque interpreter program"),
    ("git clone --config filter.lint.smudge='sh quality/lint.txt' . target\n", "opaque interpreter program"),
    ("git clone --co filter.lint.smudge='sh quality/lint.txt' . target\n", "opaque interpreter program"),
    ("git clone --conf=filter.lint.smudge='sh quality/lint.txt' . target\n", "opaque interpreter program"),
    ("git checkout HEAD^ -- Justfile\n", "opaque interpreter program"),
    ("git restore --source HEAD^ -- Justfile\n", "opaque interpreter program"),
    ("git init --template=quality/template target\n", "opaque interpreter program"),
    ("patch Justfile quality/lint.patch\n", "opaque interpreter program"),
    (
        "tar -cf payload.tar quality/lint.data; tar -xf payload.tar --transform='s|quality/lint.data|Justfile|'\n",
        "opaque interpreter program",
    ),
    ("PATH=/tmp:$PATH just clippy\n", "lint-weakening environment channel"),
    ("cd quality/decoy; just check-quality\n", "opaque interpreter program"),
    ("PATH=\"$PWD/quality/bin:$PATH\" true\n", "lint-weakening environment channel"),
    ("RIPGREP_CONFIG_PATH=quality/ripgrep.conf rg lint .\n", "lint-weakening environment channel"),
    ("COMPILER_PATH=quality/bin gcc -c quality/benign.c\n", "lint-weakening environment channel"),
    ("GCC_EXEC_PREFIX=quality/bin/ gcc -c quality/benign.c\n", "lint-weakening environment channel"),
    ("JAVA_TOOL_OPTIONS=-agentpath:quality/lint.so true\n", "lint-weakening environment channel"),
    (
        "JDK_JAVAC_OPTIONS='-processorpath quality/plugin.jar -processor AuditProcessor' true\n",
        "lint-weakening environment channel",
    ),
    (
        "javac -processorpath quality/plugin.jar -processor AuditProcessor quality/Benign.java\n",
        "opaque interpreter program",
    ),
    ("ant -f quality/build.xml lint\n", "opaque interpreter program"),
    ("EDITOR='sh quality/lint.txt' git commit --allow-empty\n", "lint-weakening environment channel"),
    ("rsync -e 'sh quality/lint.txt' localhost:/missing . || true\n", "opaque interpreter program"),
    ("cmake -P quality/lint.txt\n", "opaque interpreter program"),
    ("ctest -S quality/lint.txt || true\n", "opaque interpreter program"),
    ("ninja -f quality/lint.txt\n", "opaque interpreter program"),
    ("rustup run 1.97.0 sh quality/lint.txt\n", "lint-weakening argument"),
    ("rustup run fake cargo clippy --locked -- -D warnings\n", "opaque interpreter program"),
    ("rustup default stable\n", "lint-weakening argument"),
    ("rustup override set fake\n", "lint-weakening argument"),
    ("history -s 'sh quality/lint.txt'\nfc -s sh\n", "opaque interpreter program"),
    ("awk 'BEGIN { system(\"sh quality/lint.txt\") }'\n", "opaque interpreter program"),
    ("sed -n -e '1e sh quality/lint.txt' /etc/hosts\n", "opaque interpreter program"),
    (
        "ssh -o BatchMode=yes -o 'ProxyCommand=sh quality/lint.txt' example.invalid || true\n",
        "opaque interpreter program",
    ),
    ("ssh-agent sh quality/lint.txt\n", "opaque interpreter program"),
    ("/usr/bin/python3.12 quality/lint.txt\n", "opaque interpreter program"),
    ("python3 -m timeit 'import os; os.system(\"sh quality/lint.txt\")'\n", "opaque interpreter program"),
    ("pydoc quality/lint.py\n", "opaque interpreter program"),
    ("sqlite3 :memory: '.shell sh quality/lint.txt'\n", "opaque interpreter program"),
    (
        "dpkg --pre-invoke='sh quality/lint.txt' --unpack quality/missing.deb || true\n",
        "opaque interpreter program",
    ),
    ("wget --use-askpass=/tmp/askpass https://example.invalid/archive\n", "opaque interpreter program"),
    ("cargo +fake clippy --locked -- -D warnings\n", "lint-weakening argument"),
    ("cargo +nightly -Zscript quality/lint.rs\n", "opaque interpreter program"),
    ("cargo.exe -Z script quality/lint.rs\n", "opaque interpreter program"),
    ("cargo +nightly -Zscript -- quality/lint.rs\n", "opaque interpreter program"),
    ("rustup run nightly cargo -Z=script quality/lint.rs\n", "opaque interpreter program"),
    ("CARGO_UNSTABLE_SCRIPT=true cargo +nightly quality/lint.rs\n", "lint-weakening environment channel"),
    ("cargo doc --open\n", "opaque interpreter program"),
    ("BROWSER=quality/browser cargo doc --open\n", "opaque interpreter program"),
    ("BROWSER=quality/browser true\n", "lint-weakening environment channel"),
    ("CARGO_DOC_BROWSER=quality/browser true\n", "lint-weakening environment channel"),
    ("cargo install --path quality/helper\n", "opaque interpreter program"),
    ("cargo rustc -- -C linker=quality/lint\n", "opaque interpreter program"),
    ("rustup toolchain link fake /tmp/toolchain\n", "lint-weakening argument"),
    ("setarch --uname-2.6 sh quality/lint.txt\n", "opaque interpreter program"),
    ("linux32 -- sh quality/lint.txt\n", "opaque interpreter program"),
    ("linux64 -- sh quality/lint.txt\n", "opaque interpreter program"),
    ("sg \"$(id -gn)\" -c 'sh quality/lint.txt'\n", "opaque interpreter program"),
    ("su \"$(id -un)\" -c 'sh quality/lint.txt'\n", "opaque interpreter program"),
    ("runuser \"$(id -un)\" -c 'sh quality/lint.txt'\n", "opaque interpreter program"),
    (
        "start-stop-daemon --start --name localhold --startas /bin/sh --chdir . -- quality/lint.txt\n",
        "opaque interpreter program",
    ),
    ("shopt -s expand_aliases\nalias lint='sh quality/lint.txt'\nlint\n", "opaque interpreter program"),
    ("cat <(sh quality/lint.txt)\n", "lint-weakening argument"),
    ("coproc sh quality/lint.txt\n", "opaque interpreter program"),
    ("mapfile -C 'sh quality/lint.txt' -c 1 </etc/hosts\n", "opaque interpreter program"),
    ("readarray -tC 'sh quality/lint.txt' -c 1 </etc/hosts\n", "opaque interpreter program"),
    ("cat <<DOC\n$(sh quality/lint.txt)\nDOC\n", "opaque interpreter program"),
    (
        "tar --checkpoint=1 --checkpoint-action=exec='sh quality/lint.txt' -cf archive.tar .\n",
        "opaque interpreter program",
    ),
    ("sort --compress-program=quality/lint.txt /etc/hosts\n", "opaque interpreter program"),
    ("printf 'x\\n' | split -l 1 --filter='sh quality/lint.txt'\n", "opaque interpreter program"),
    ("unzip -oq target/payload.zip\n", "opaque interpreter program"),
    ("zip -q -T -TT 'sh quality/lint.txt' archive.zip /etc/hosts\n", "opaque interpreter program"),
    ("printf '%s\\n' \"$(just check-quality)\"\n", "lint-weakening argument"),
    ("set +e; just check-quality; true\n", "lint-weakening argument"),
    ("{\n just check-quality\n true\n} || true\n", "lint-weakening argument"),
    ("(\n cargo test --locked\n true\n) || true\n", "lint-weakening argument"),
    ("case \"$mode\" in\n checked) just check-quality; true ;;\nesac || true\n", "lint-weakening argument"),
    ("if test -f Cargo.toml; then\n just check-quality\n true\nfi || true\n", "lint-weakening argument"),
    ("npm exec -c 'sh quality/lint.txt'\n", "opaque interpreter program"),
    ("docker run --rm -v \"$PWD:/repo\" -w /repo rust:latest sh quality/lint.txt\n", "opaque interpreter program"),
    ("npx -c 'sh quality/lint.txt'\n", "opaque interpreter program"),
    ("java quality/Lint.java\n", "opaque interpreter program"),
    ("gradle -b quality/lint.data help\n", "opaque interpreter program"),
    ("./gradlew --build-file quality/lint.data help\n", "opaque interpreter program"),
    ("just --justfile quality/lint.data check-quality\n", "opaque interpreter program"),
    ("make -E 'all:; sh quality/lint.txt' all\n", "opaque interpreter program"),
    ("HOME=quality bash -i quality/lint.txt\n", "opaque interpreter program"),
    ("rg --pre='sh quality/lint.txt' lint .\n", "opaque interpreter program"),
    ("cp quality/lint.data Justfile\n", "opaque interpreter program"),
    ("destination=Justfile; cp quality/lint.data \"$destination\"\n", "opaque interpreter program"),
    ("iconv -f UTF-8 -t UTF-8 quality/lint.data -o Justfile\n", "opaque interpreter program"),
    ("curl --silent --output Justfile \"file://$PWD/quality/lint.data\"\n", "opaque interpreter program"),
    ("curl -O \"file://$PWD/quality/Justfile\"\n", "opaque interpreter program"),
    ("cat quality/lint.data > Justfile\n", "opaque interpreter program"),
    ("openssl list -provider-path quality -provider lint\n", "opaque interpreter program"),
    ("openssl base64 -d -in quality/Justfile.b64 -out Justfile\n", "opaque interpreter program"),
    ("openssl req -engine lint -new\n", "opaque interpreter program"),
    ("OPENSSL_CONF=quality/openssl.cnf openssl version\n", "lint-weakening environment channel"),
    ("OPENSSL_CONF_INCLUDE=quality openssl version\n", "lint-weakening environment channel"),
    ("OPENSSL_ENGINES=quality openssl version\n", "lint-weakening environment channel"),
    ("OPENSSL_MODULES=quality openssl version\n", "lint-weakening environment channel"),
    ("cscript.exe //nologo quality/lint.vbs\n", "opaque interpreter program"),
    ("wscript quality/lint.wsf\n", "opaque interpreter program"),
    ("dotnet run --project quality/lint.csproj\n", "opaque interpreter program"),
    ("gcc -wrapper sh,quality/lint.txt -c quality/input.c\n", "opaque interpreter program"),
    ("rustc quality/benign.rs --extern serde=quality/libserde.so\n", "opaque interpreter program"),
    ("objcopy -I binary -O binary quality/Justfile Justfile\n", "opaque interpreter program"),
    ("nm --plugin quality/lint.so /bin/true\n", "opaque interpreter program"),
    ("ranlib --plugin=quality/lint.so quality/archive.a\n", "opaque interpreter program"),
    ("rake --rakefile quality/lint.txt\n", "opaque interpreter program"),
    ("RUBYOPT=-r./quality/lint gem --version\n", "lint-weakening environment channel"),
    ("PERL5OPT='-Iquality -Mlint' prove --version\n", "lint-weakening environment channel"),
    ("ld.so quality/lint\n", "opaque interpreter program"),
    ("/lib64/ld-linux-x86-64.so.2 quality/lint\n", "opaque interpreter program"),
    ("go run quality/lint.go\n", "opaque interpreter program"),
    ("go.exe -C quality run lint.go\n", "opaque interpreter program"),
    ("go generate ./quality/helper\n", "opaque interpreter program"),
    ("go test ./quality/helper\n", "opaque interpreter program"),
    ("go build -toolexec=quality/lint ./...\n", "opaque interpreter program"),
    ("CCACHE_DISABLE=1 ccache sh quality/lint.txt\n", "opaque interpreter program"),
    ("sccache sh quality/lint.txt\n", "opaque interpreter program"),
    ("distcc sh quality/lint.txt\n", "opaque interpreter program"),
    ("pip3.12 install quality/helper\n", "opaque interpreter program"),
    ("mise x -- sh quality/lint.txt\n", "lint-weakening argument"),
    ("cmd.exe /d /s /c \"powershell.exe -NoProfile -EncodedCommand payload\"\n", "opaque interpreter program"),
    ("$'\\x73\\x68' quality/lint.txt\n", "opaque interpreter program"),
    ("runner=sh\n\"$runner\" quality/lint.txt\n", "opaque interpreter program"),
    ("swift quality/lint.swift\n", "opaque interpreter program"),
    ("m4 quality/lint.m4\n", "opaque interpreter program"),
];
